import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

// Inter is the single typeface for the entire site. Weights 400 / 500 / 600 / 700.
// No second font family is loaded by design.
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const TITLE = "Prajit Nandeshwar, Lead Product Designer";
const DESCRIPTION =
  "Lead Product Designer at Clear, shipping enterprise compliance software end to end. Tax GRC, AI-augmented design, and design systems across 8 products and 4 countries.";

export const metadata: Metadata = {
  // metadataBase sets the origin Next.js prepends to any relative URL
  // inside this metadata object, including the OG image generated by
  // app/opengraph-image.tsx. Without it, link unfurlers like LinkedIn
  // and Slack cannot resolve the image and the card fails to render.
  metadataBase: new URL("https://prajitnandeshwar.in"),
  title: {
    default: TITLE,
    // Per-route metadata that sets only `title` (eg the case study) is
    // automatically suffixed via this template, so "Notice Tracker"
    // becomes "Notice Tracker · Prajit Nandeshwar" in the tab.
    template: "%s · Prajit Nandeshwar",
  },
  description: DESCRIPTION,
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "/",
    siteName: "Prajit Nandeshwar",
    title: TITLE,
    description: DESCRIPTION,
    // The opengraph-image.tsx convention auto-attaches the generated
    // image here; declaring it explicitly is unnecessary.
  },
  twitter: {
    card: "summary_large_image",
    title: TITLE,
    description: DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${geistMono.variable} h-full antialiased scroll-smooth scroll-pt-14`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground selection:bg-foreground selection:text-background overflow-x-hidden">
        {children}
        <Analytics />
      </body>
    </html>
  );
}
