import { ImageResponse } from "next/og";

// Dynamic Open Graph image, generated by Next.js the first time it is
// requested and then cached. Cream background, Inter-ish system stack
// (next/og does not have access to Google Fonts inline; system-ui
// approximates Inter on macOS and Windows), amber accent on the role.
// Outputs at exactly the 1200 x 630 size LinkedIn, Twitter, and Slack
// crop to when unfurling links.

export const runtime = "edge";
export const alt = "Prajit Nandeshwar, Lead Product Designer";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default async function OG() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          background: "#FAFAF9",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          padding: "96px",
          fontFamily:
            'system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
          color: "#1F1F1E",
        }}
      >
        <div
          style={{
            fontSize: 24,
            color: "#9C9C97",
            letterSpacing: 4,
            textTransform: "uppercase",
            marginBottom: 36,
            fontWeight: 600,
          }}
        >
          Portfolio
        </div>
        <div
          style={{
            fontSize: 104,
            fontWeight: 600,
            letterSpacing: -3,
            lineHeight: 1.04,
            marginBottom: 28,
          }}
        >
          Prajit Nandeshwar
        </div>
        <div
          style={{
            display: "flex",
            fontSize: 44,
            color: "#6B6B68",
            fontWeight: 400,
          }}
        >
          Lead Product Designer
          <span style={{ color: "#D97706" }}>.</span>
        </div>
      </div>
    ),
    { ...size },
  );
}
